### ISSUE TITLE
plugin doesn't work since latest IntelliJ IDEA update

### ISSUE THREAD

**Issue by YA2O** [chashnikov/IntelliJ-presentation-assistant#17]
IntelliJ IDEA 2016.3.5
Build #IU-163.13906.18, built on March 6, 2017
JRE: 1.8.0_112-release-408-b6 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

running on MacOS 10.12.3

**Comment by heyoni** [comment]
Same issue here but with the following:

> PyCharm 2017.1
Build #PY-171.3780.115, built on March 24, 2017
JRE: 1.8.0_112-release-736-b13 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.4

No errors in console log and the popup just isn't showing up.

Anyone remember which version it last worked with? I may downgrade.

**Comment by ShevaDavid** [comment]
Same problem with
IntelliJ IDEA 2017.1.3
Build #IU-171.4424.56, built on May 12, 2017
JRE: 1.8.0_112-release-736-b21 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.4.0-78-generic

**Comment by chashnikov** [comment]
Are there any exceptions in idea.log (Help | Show Log)?

**Comment by Malanius** [comment]
I have the same issue. There are no errors in the log, only mention of the plugin is in line:
`... INFO - llij.ide.plugins.PluginManager - Loaded custom plugins:  Presentation Assistant (1.0.1)...`
Plugin settings seem to work, but no pop-ups are displaying.

IntelliJ IDEA 2018.1 (Ultimate Edition)
Build #IU-181.4203.550, built on March 26, 2018
JRE: 1.8.0_152-release-991-b1 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

(for me it is not working since 2017.1 if I remember correctly)

**Comment by mikezx6r** [comment]
See answer here https://github.com/chashnikov/IntelliJ-presentation-assistant/issues/15

Need to enable 'Descriptions of Actions' on View Menu and then it works correctly. Needs a documentation update, but this is a nice way to turn it on/off.
