### ISSUE TITLE
Please consider adding mutliple caret shortcuts

### ISSUE THREAD

**Issue by helenjoscott** [chashnikov/IntelliJ-presentation-assistant#45]
As detailed here https://www.jetbrains.com/help/idea/working-with-source-code.html?keymap=primary_windows#multiple_cursor

Specifically:

**Add for Windows**
To add or remove multiple carets, press and hold Shift+Alt and click at the next location of the caret.

Alternatively, to add multiple carets, you can press Ctrl twice, and then without releasing it, press the Up or Down arrow keys. You can also make a multiple selection by pressing Shift+Alt and dragging the caret. 

**Add for macOS**
To add or remove multiple carets, press and hold ⇧⌥ and click at the next location of the caret.

Alternatively, to add multiple carets, you can press ⌥ twice, and then without releasing it, press the Up or Down arrow keys. You can also make a multiple selection by pressing ⇧⌥ and dragging the caret. 

**Column Select Mode Update**
Also please add the Windows one for Column Select Mode (currently just macOS):
You can make a multiple selection of code in columns. To enable or disable the column selection mode, press Alt+Shift+Insert or use the context menu of the editor.

**Comment by chashnikov** [comment]
I've just uploaded version 1.0.8 which should show double-ctrl shortcuts for adding new carets properly.

Regarding "Column Select Mode": it works properly for me when invoked via shortcut:
![image](https://user-images.githubusercontent.com/978014/106765642-12906c80-664a-11eb-866d-91bddb553800.png)

Regarding mouse shortcuts: there is no simple way to reliable show proper description when an action was invoked by mouse, because there is no single point in IntelliJ API to process such actions, we would need to implement such logic separately for each action. If it's really important for you, please file a separate issue about that. However note that IntelliJ IDEA is keyboard-centric IDE so it's better to use keyboard shortcuts instead of mouse in screencasts and presentations.
