### ISSUE TITLE
Not compatible with IntelliJ IDEA 2023.3

### ISSUE THREAD

**Issue by pdob-git** [chashnikov/IntelliJ-presentation-assistant#59]
### Not compatible with IntelliJ IDEA 2023.3
Presentation Assistant 1.0.10 is not compatible with IntelliJ IDEA 2023.3
![image](https://github.com/chashnikov/IntelliJ-presentation-assistant/assets/75912982/990def0e-aad4-4c3e-8938-5ada0527c4e8)

When is possible to have my favorite plugin back? ;-)

**Comment by chashnikov** [comment]
Since 2023.3 functionality of the plugin is included to IntelliJ Platform, so it should be available in all IntelliJ-based IDEs out of the box, see [the help](https://www.jetbrains.com/help/idea/presentation-assistant.html). If you have the plugin installed in older version of the IDE, when you run IntelliJ IDEA 2023.3 for the first time, it should suggest migrating settings from the previous version, and if you agree, settings of the plugin should be migrated automatically. If this doesn't happen for some reason, just enable "Settings | Appearance & Behavior | Presentation Assistant | Show action names and shortcuts in popup" option by hand.

**Comment by muescha** [comment]
Those are good news.

Could you also update the plugin description here: https://plugins.jetbrains.com/plugin/7345-presentation-assistant

**Comment by chashnikov** [comment]
@muescha surely, I'm working on it. Unfortunately, in order to update a plugin's description one needs to upload a new version of the plugin, it takes some time.

**Comment by muescha** [comment]
thx a lot :)

**Comment by muescha** [comment]
I submitted a review for the plugin and included a quote from your statement. I hope that's alright!

**Comment by pdob-git** [comment]
Great news.
@chashnikov Thank you very much. I have activated a new option in 2023.3
